[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/*"
  to = "/page-not-found/"
  status = 404

[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"
